version: '3.8'
services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

